2021-09-19 09:27:10,389 INFO    Thread-323:316720 [wandb_setup.py:_flush():69] setting env: {'root_dir': '/grid/koo/home/toneyan/profile/QuantPred', 'entity': 'toneyan', 'project': 'FINETUNE_BASENJIW1b64_POISSON_AUGM_E40', 'run_id': 'b21l9feq', 'sweep_param_path': '/grid/koo/home/toneyan/profile/QuantPred/wandb/sweep-6c2mqhnm/config-b21l9feq.yaml', 'sweep_id': '6c2mqhnm'}
2021-09-19 09:27:10,389 INFO    Thread-323:316720 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-19 09:27:10,389 INFO    Thread-323:316720 [wandb_init.py:_log_setup():337] Logging user logs to /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210919_092710-b21l9feq/logs/debug.log
2021-09-19 09:27:10,389 INFO    Thread-323:316720 [wandb_init.py:_log_setup():338] Logging internal logs to /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210919_092710-b21l9feq/logs/debug-internal.log
2021-09-19 09:27:10,390 INFO    Thread-323:316720 [wandb_init.py:init():370] calling init triggers
2021-09-19 09:27:10,390 INFO    Thread-323:316720 [wandb_init.py:init():377] wandb.init called with sweep_config: {'add_dropout': True, 'bin_size': 1, 'data_dir': 'datasets/complete/random_chop/i_3072_w_1/', 'filtN_1': 64, 'filtN_2': 256, 'filtN_3': 256, 'filtN_4': 256, 'filtN_5': 64, 'l_rate': 0.001, 'loss_fn': 'poisson', 'model_fn': 'basenji_w1_b64', 'num_epochs': 40, 'window_size': 2048}
config: {}
2021-09-19 09:27:10,390 INFO    Thread-323:316720 [wandb_init.py:init():419] starting backend
2021-09-19 09:27:10,390 INFO    Thread-323:316720 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-19 09:27:10,392 INFO    Thread-323:316720 [backend.py:ensure_launched():135] starting backend process...
2021-09-19 09:27:10,414 INFO    Thread-323:316720 [backend.py:ensure_launched():140] started backend process with pid: 3003242
2021-09-19 09:27:10,415 INFO    Thread-323:316720 [wandb_init.py:init():424] backend started and connected
2021-09-19 09:27:10,418 INFO    Thread-323:316720 [wandb_run.py:_config_callback():872] config_cb None None {'add_dropout': True, 'bin_size': 1, 'data_dir': 'datasets/complete/random_chop/i_3072_w_1/', 'filtN_1': 64, 'filtN_2': 256, 'filtN_3': 256, 'filtN_4': 256, 'filtN_5': 64, 'l_rate': 0.001, 'loss_fn': 'poisson', 'model_fn': 'basenji_w1_b64', 'num_epochs': 40, 'window_size': 2048}
2021-09-19 09:27:10,418 INFO    Thread-323:316720 [wandb_init.py:init():472] updated telemetry
2021-09-19 09:27:10,419 INFO    Thread-323:316720 [wandb_init.py:init():491] communicating current version
2021-09-19 09:27:11,028 INFO    Thread-323:316720 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.12.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-19 09:27:11,028 INFO    Thread-323:316720 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-09-19 09:27:14,083 ERROR   Thread-324:316720 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-19 09:27:14,083 ERROR   Thread-324:316720 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-19 09:27:14,827 ERROR   Thread-2  :316720 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-19 09:27:14,828 ERROR   Thread-2  :316720 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-19 09:27:19,165 INFO    Thread-323:316720 [wandb_init.py:init():529] starting run threads in backend
2021-09-19 09:27:20,293 INFO    Thread-323:316720 [wandb_run.py:_console_start():1623] atexit reg
2021-09-19 09:27:20,294 INFO    Thread-323:316720 [wandb_run.py:_redirect():1497] redirect: SettingsConsole.REDIRECT
2021-09-19 09:27:20,294 INFO    Thread-323:316720 [wandb_run.py:_redirect():1502] Redirecting console.
2021-09-19 09:27:20,294 ERROR   Thread-323:316720 [wandb_run.py:_redirect():1561] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_run.py", line 1554, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-09-19 09:27:20,295 INFO    Thread-323:316720 [wandb_init.py:init():554] run started, returning control to user process
2021-09-19 09:27:24,197 ERROR   Thread-2  :316720 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-19 09:27:24,197 ERROR   Thread-2  :316720 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-19 09:27:41,865 ERROR   Thread-2  :316720 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-19 09:27:41,865 ERROR   Thread-2  :316720 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-19 09:27:51,046 INFO    Thread-323:316720 [wandb_run.py:finish():1293] finishing run toneyan/FINETUNE_BASENJIW1b64_POISSON_AUGM_E40/b21l9feq
